feat: indexer
eukarya-inc/reearth-plateauview pull request #49
Opened 2022-11-22 11:32 UTC by pyshx

2022-11-25 04:29 UTC, rot1024 requested changes

2022-11-25 04:29 UTC, rot1024 commented on server/indexer/index.go
> +	Values map[string]*EnumValue
```suggestion
	Kind   string                `json:"kind"`
	Values map[string]*EnumValue `json:"values"`
```

All struct fields that can be serialized or deserialized as JSON should have a `json` tag. CamelCase with the first letter capitalized is not very common in JSON.

2022-11-25 04:29 UTC, rot1024 commented on server/indexer/testdata/config.json
> +}
Remove this file

2022-11-25 04:29 UTC, rot1024 commented on server/indexer/util_test.go
> +package indexer
Remove this file or add unit tests

2022-11-25 04:29 UTC, rot1024 commented on server/indexer/cesium_math.go
> +	_DEGREES_PER_RADIAN = 180.0 / math.Pi
```suggestion
	Epsilon1           = 0.1
	Epsilon12          = 0.000000000001
	Epsilon14          = 0.00000000000001
	Pi     = math.Pi
	TwoPi = 2 * math.Pi
	DegreesPerRadian = 180.0 / math.Pi
```

(Note that this suggestion is handwritten and not formatted)

Adding an underscore at the beginning is not particularly meaningful in Golang and is not very common. Golang rarely uses `snake_case`. Use `camelCase` (private) or `CamelCase` (public). In this case CamelCase is ok.

2022-11-25 04:29 UTC, rot1024 commented on server/indexer/indexer_test.go
> +	}
Do not run the test data file if it does not exist.

2022-11-25 04:29 UTC, rot1024 commented on server/indexer/util.go
> +}
You can use `util.TryMap` in `reearth/reearthx` instead of this function. It has `TryMap[T, K any]([]T, func(T) (K, error)) ([]K, error)`

2022-11-25 04:29 UTC, rot1024 commented on server/indexer/indexer.go
> +	tileset, err := tiles.Open(tilesetFile)
```suggestion
	tileset, err := tiles.Open("tileset.json") // or config.TilesetJSONPath
```

I believe the specification specifies that the file name is `tileset.json`, but if you need flexibility, you should be able to set that in `IndexerConfig`.

2022-11-25 04:29 UTC, rot1024 commented on server/indexer/indexer_config.go
> +type IndexesConfig struct {
Better naming conventions:

```suggestion
type Config struct {
```

`Config` is enough, as users of this package requires writing `indexer.Config{}`, but it is easily understandable what config it is.

In general, if the package name is `indexer`:

```go
package indexer

type Indexer struct {} // it's ok
type IndexerHogehoge struct {} // -> Hogehoge

func NewIndexer() *Indexer // -> New
func NewIndexerHogehoge() *IndexerHogehoge // -> NewHogehoge
```

2022-11-25 04:29 UTC, rot1024 commented on server/.gitignore
> +indexer/testdata/tileset.json
```suggestion
indexer/testdata
```

2022-11-25 07:32 UTC, pyshx commented on server/indexer/indexer.go
> +func Indexer(tilesetFile, indexConfigFile, outDir string) error {
Gotcha!
In that case, it'll not just be IndexRoot which we'll have to return it be more like
```suggestion
func Indexer(config Config, fs io.FS) (IndexBuilder, []map[string]string, IndexRoot )
```


Context: 

- IndexBuilder stores the location of each feature at `resultsData.csv` which were getting saved as csv as well e.g `4-34.csv` in the image attached below
![Capture](https://user-images.githubusercontent.com/42397980/203924917-8dfec6d8-4256-46ba-8bb8-db56f0e73443.PNG)

-  []map[string]string will the be the `resultsData.csv` content

2022-11-25 07:32 UTC, pyshx commented on server/indexer/index_builder.go
> +	}
Thanks.

2022-12-16 14:03 UTC, rot1024 approved these changes

2022-12-16 15:56 UTC, merged